# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: {
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    timeout = 10;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-label/swap";}
  ];

  networking = {
    useDHCP = false; # Disable global DHCP
    interfaces.eno2.useDHCP = lib.mkDefault true;
    interfaces.enp2s0.useDHCP = lib.mkDefault true;
    interfaces.eno1.useDHCP = false; # Disable DHCP for the interface you want to add to the bridge
    interfaces.br0.useDHCP = true;
    interfaces.br0.macAddress = "3c:ec:ef:b5:bf:6e"; # Set the MAC address of the bridge from eno1
    bridges = {
      "br0" = {
        interfaces = [ "eno1" ];
      };
    };

  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
