# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 1;
  };
  boot.kernelModules = [
    "kvm-intel"
    "usb_storage"
    "kvmgt"
    "vfio-iommu-type1"
    "mdev"
  ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [
    "i915.disable_display=1"
    "i915.enable_gvt=1"
    "intel_iommu=on"
    "iommu=pt"
  ];

  # disabling as it conflicts with proxmox using mediated gpu passthrough
  # virtualisation.kvmgt.vgpus = {
  #   "i915-GVTg_V5_8" = {
  #     uuid = [
  #       "9f905394-d4d7-11ee-9a00-937582b91b7c"
  #       "31cb043a-d4e1-11ee-9357-7b7a0730baf4"
  #     ]; # uuid generated with 'nix shell nixpkgs#libossp_uuid -c uuid'
  #   };
  # };

  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
    timeout = 10;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  hardware.ksm.enable = true;

  swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
